development:
  adapter: postgresql
  database: impulsideas_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  database: impulsideas_test
  host: localhost

production:
  adapter: postgresql
  database: impulsideas_production
  host: localhost
